name: Build PayURLHook Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Theos
      run: |
        set -e
        brew install ldid xz
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip -q master.zip
        mv sdks-master/*.sdk $GITHUB_WORKSPACE/theos/sdks/
        rm -rf sdks-master master.zip
        ls $GITHUB_WORKSPACE/theos/sdks/

    - name: Build deb
      env:
        THEOS: ${{ github.workspace }}/theos
      run: |
        set -e
        make package FINALPACKAGE=1

    - name: Upload deb
      uses: actions/upload-artifact@v4
      with:
        name: PayURLHook-deb
        path: packages/*.deb
